commit message
mate-academy/layout_hello-world pull request #1779
Opened 2022-06-02 08:21 UTC by Evgeniy-Kulish

2022-06-02 13:47 UTC, ArtemTopolskyi requested changes
Добавь ссылки на демо page в описание пулл реквеста на гитхабе

2022-06-02 13:47 UTC, ArtemTopolskyi commented on src/index.html
> +</html>
добавь пустую строку в конце файла

2022-06-02 13:47 UTC, ArtemTopolskyi commented on src/index.html
> +  Hello, world!
добавь отступы к строке

2022-06-02 13:47 UTC, ArtemTopolskyi commented on src/style.css
> +}
в этом задании нет необходимости в дополнительных стилях

2022-06-03 09:31 UTC, Evgeniy-Kulish commented
> Добавь ссылки на демо page в описание пулл реквеста на гитхабе

- [DEMO LINK](https://Evgeniy-Kulish.github.io/layout_hello-world/)
- [TEST REPORT LINK](https://Evgeniy-Kulish.github.io/layout_hello-world/report/html_report/)

2022-06-03 09:32 UTC, Evgeniy-Kulish commented
- [DEMO LINK](https://Evgeniy-Kulish.github.io/layout_hello-world/)
- [TEST REPORT LINK](https://Evgeniy-Kulish.github.io/layout_hello-world/report/html_report/)

2022-06-03 09:32 UTC, closed without merging

2022-06-03 09:33 UTC, Evgeniy-Kulish commented on src/index.html
> +</html>
добавил

2022-06-03 09:33 UTC, Evgeniy-Kulish commented on src/index.html
> +  Hello, world!
в строке добавил два пробела

2022-06-03 09:36 UTC, Evgeniy-Kulish commented on src/style.css
> +}
Вроде все исправил. Спасибо!  Добавление стилей - это ведь не ошибка?