oksana-logos-frontend
mate-academy/layout_hello-world pull request #1937
Opened 2022-07-06 20:36 UTC by oksana-logos-frontend

https://oksana-logos-frontend.github.io/layout_hello-world/
https://oksana-logos-frontend.github.io/layout_hello-world/report/html_report/

2022-07-06 20:41 UTC, closed without merging

2022-07-11 08:57 UTC, danylo-onishchuk requested changes

2022-07-11 08:57 UTC, danylo-onishchuk commented on src/index.html
> +</html>
в конце файла нужно всегда оставлять пустую строку

2022-07-11 10:05 UTC, oksana-logos-frontend commented on src/index.html
> +</html>
додала в кінець файлу пусту стрічку

2022-07-13 07:14 UTC, danylo-onishchuk approved these changes