first-commit
mate-academy/layout_hello-world pull request #897
Opened 2021-05-24 10:40 UTC by vitaliy-martynyuk

2021-05-24 10:47 UTC, solaryasha requested changes
Додай в опис пул реквест посилання на демку і тести

2021-05-24 10:47 UTC, solaryasha commented on src/index.html
> +</html>
Описав проблему в цьому треді -https://mateacademy.slack.com/archives/C021CDS2J79/p1621846318174900

2021-05-24 10:50 UTC, vitaliy-martynyuk commented on src/index.html
> +</html>
![image](https://user-images.githubusercontent.com/84335906/119337036-07b02500-bc97-11eb-8ec8-2ee755951e2e.png)

2021-05-24 10:51 UTC, vitaliy-martynyuk commented on src/index.html
> +</html>
я впринципі зробив так як в тій інструкції пише, чи треба ще щось змінити?
а на рахунок опису, це треба новий коміт робити, чи можна модіфаїти цей?

2021-05-24 11:32 UTC, solaryasha requested changes
У тебе непройдені тести, ще раз уважно перечитай умову
<img width="1298" alt="Screenshot 2021-05-24 at 14 32 06" src="https://user-images.githubusercontent.com/32794096/119341811-e05c5680-bc9c-11eb-81bf-8f0cbc35dbac.png">

2021-05-25 13:51 UTC, vitaliy-martynyuk commented
перевстановив парсель, тест проходить, сторінку відкриває, але сама тестова сторінка(хоч і з пройденим тестом) видає нову помилку

2021-05-25 15:50 UTC, solaryasha approved these changes
Well done !

2021-11-25 08:55 UTC, closed without merging